# -*- coding: utf-8 -*-
"""Copy of Explainable_Research_Paper_Retrieval_and_Recommendation_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pg0ouR596RUjzcmYZr1w9nhIP2431mJC

# Explainable Research Paper Retrieval and Recommendation System
## Semantic Search • Summarization • Keyword Extraction • Explainable AI • Difficulty Analysis
"""

# Install all required external libraries
!pip install datasets transformers==4.46.3 keybert==0.8.5 faiss-cpu gliner

"""## Dataset Loading"""

from datasets import load_dataset

# Load the Machine Learning ArXiv Papers dataset from Hugging Face
dataset = load_dataset(
    "CShorten/ML-ArXiv-Papers",
    split="train"
)

print(dataset)

dataset[0]

"""## Data Preprocessing"""

import pandas as pd

# Convert Hugging Face dataset into a Pandas DataFrame and display first few rows
df = pd.DataFrame(dataset)
df

df.columns

df = df[['title','abstract']]

df

df.shape

# Select only the first 15,000 research papers.
# This reduces computation time while generating embeddings.
df = df.head(15000)
df.shape

df.isnull().sum()

# Combine the title and abstract into a single column.This combined text will be used for generating embeddings.
df["paper_text"] = df["title"] + " " + df["abstract"]

df["paper_text"].head()

# Display the paper_text column as a DataFrame
df[["paper_text"]].head()

type(df[["paper_text"]])

print(df['paper_text'].iloc[0])

"""## Embedding Generation

**Load Sentence Transformer**
"""

# Import SentenceTransformer
# It converts text into dense numerical vectors (embeddings).
from sentence_transformers import SentenceTransformer

# Load the pre-trained MiniLM embedding model
model = SentenceTransformer(
    'sentence-transformers/all-MiniLM-L6-v2'
)

print(type(model))

df["paper_text"]=df["paper_text"].str.replace("\n"," ",regex= False)

df["paper_text"] = df["paper_text"].str.strip()

# Select the first research paper for testing the embedding model.
sample_text = df["paper_text"].iloc[0]
sample_text

"""**Generate Embedding**"""

# Convert the sample paper into a numerical embedding vector.
embedding = model.encode(sample_text)

print(type(embedding))
print(embedding.shape)

# Display the first 56 values of the embedding vector
embedding[:56]

"""**Generate Embeddings for First 5 Papers**"""

# Generate embeddings for the first 5 research papers.
sample_embedding = model.encode(
    df["paper_text"].head(5).to_list()
)

# Check the shape of the generated embeddings
sample_embedding.shape

"""**Check Similarity of Same Paper**"""

# Import cosine similarity function
# Cosine similarity measures how similar two vectors are.

from sklearn.metrics.pairwise import cosine_similarity

# Compare the first paper with itself. Similarity should be close to 1.0.
similarity = cosine_similarity(
    sample_embedding[0].reshape(1, -1),
    sample_embedding[0].reshape(1, -1)
)
print(similarity)

"""**Compare Two Different Papers**"""

# Compare the first paper with the second paper.
# Since they are different research papers, the similarity score will be less than 1.

similarity = cosine_similarity(
    sample_embedding[0].reshape(1, -1),
    sample_embedding[1].reshape(1, -1)
)
print(similarity)

# Compare the first paper with the remaining four papers.
# This helps verify that semantically similar papers receive higher similarity scores.

for i in range(1, 5):
    sim = cosine_similarity(
        sample_embedding[0].reshape(1, -1),
        sample_embedding[i].reshape(1, -1)
    )

    print(f"Paper 0 vs Paper {i}")
    print(sim)

"""**Generate full embedding on 15000 research papers**"""

# Generate embeddings for all research papers.
# Batch processing is used to improve speed and memory efficiency.

embedding = model.encode(
    df["paper_text"].to_list(),
    batch_size=32,
    show_progress_bar=True
)

print(embedding.shape)
print(type(embedding))

embedding.dtype

"""**Import FAISS**"""

import faiss

"""**Normalize Embeddings**"""

# Normalize all embedding vectors using L2 normalization.
# This allows Inner Product (IP) similarity to behave like Cosine Similarity.
faiss.normalize_L2(embedding)

"""## FAISS Index Creation"""

# IndexFlatIP performs exact similarity search using Inner Product.
index = faiss.IndexFlatIP(384)

# Add all embedding vectors to the FAISS index.
index.add(embedding)

"""**Generate and Save Embeddings**"""

# Import libraries for saving embeddings and checking whether files already exist.
# Check whether the embeddings file already exists. If it exists, load the saved embeddings to save computation time.
# Otherwise, generate embeddings and save them for future use.
import os
import numpy as np
if os.path.exists("paper_embeddings.npy"):
    print("Loading saved embeddings")
    embeddings = np.load("paper_embeddings.npy")
else:
    print("Generating embeddings")
    embeddings = model.encode(
        df["paper_text"].tolist(),
        batch_size=32,
        show_progress_bar=True
    )

    # Save embeddings as a NumPy file
    np.save("paper_embeddings.npy", embeddings)
    print("Embeddings saved successfully!")

"""**Save or Load FAISS Index**"""

# Check whether the FAISS index already exists.
# If it exists, load it directly.Otherwise, create a new FAISS index, add embeddings, and save it for future use.

if os.path.exists("paper_faiss.index"):
    print("Loading existing FAISS index")
    index = faiss.read_index("paper_faiss.index")

else:
    print("Creating new FAISS index")

    # Normalize embeddings before adding them to the FAISS index
    faiss.normalize_L2(embeddings)

    # Create FAISS Index using Inner Product similarity
    index = faiss.IndexFlatIP(384)

    # Add embeddings into the index
    index.add(embeddings)

    # Save the FAISS index
    faiss.write_index(index, "paper_faiss.index")

    print("FAISS index saved successfully!")

# Display the total number of research papers stored inside the FAISS index.
print(index.ntotal)

"""**User Query**"""

# Enter the search query.
# The recommendation system will retrieve semantically similar research papers.
query = "deep learning for medical image analysis"

"""**Generate Query Embedding**"""

# Convert the user query into an embedding vector.
query_embedding = model.encode([query])

# Display embedding shape
query_embedding.shape

"""**Normalize Query Embedding**"""

# Normalize the query embedding.
# This ensures that Inner Product similarity behaves like Cosine Similarity.
faiss.normalize_L2(query_embedding)

"""**Search Similar Papers**"""

# Search the FAISS index.

# D = Similarity Scores
# I = Indices of retrieved research papers
# k = Number of top similar papers to retrieve

D, I = index.search(query_embedding, 5)

print(D)
print(I)

"""**Display Retrieved Paper Title and Abstract**"""

print(df.iloc[10466]["title"])

print(df.iloc[10466]["abstract"])

"""**Display Another Retrieved Paper**"""

print(df.iloc[11873]["title"])

# Observation:
# Sometimes the retrieved papers may not contain the exact keywords used in the query.
# This is expected because Sentence Transformers perform Semantic Search instead of Keyword Search.
# Semantic Search retrieves papers based on meaning, not exact word matching.

"""## Semantic Search"""

# Create a reusable function to search the top-k similar research papers.
def search_paper(query, k=5):
    query_embedding = model.encode([query])
    faiss.normalize_L2(query_embedding)
    D, I = index.search(query_embedding, k)
    return D, I

"""**Test Search Function**"""

D,I = search_paper("deep learning for medical image analysis")
print(D)
print(I)

"""**Display Search Results**"""

# Update the search function to display the similarity score,paper title, and a portion of the abstract.
def search_paper(query,k=5):
  query_embedding = model.encode([query])
  faiss.normalize_L2(embeddings)
  D,I = index.search(query_embedding,k)
  for score,idx in zip(D[0],I[0]):
    print("Similarity Score",score)
    print("Paper Title",df.iloc[idx]["title"])
    print("Paper Abstract",df.iloc[idx]["abstract"][:500])
    print()

"""**Search Research Papers**"""

# Retrieve and display the top matching research papers.
search_paper("deep learning for medical image analysis")

"""## Research Paper Summarization"""

# BART (Bidirectional and Auto-Regressive Transformers)
# Encoder-Decoder model that combines:
# - BERT-like understanding (encoder)
# - GPT-like text generation (decoder)
# Used here for abstractive text summarization (generates new summary, not copy-paste).

# Note:
# Transformers library updates frequently, so always pin a specific version
# (e.g., transformers==4.46.3) to avoid compatibility issues and ensure stable results.

"""**Load the BART Summarization Model**"""

# Import the pipeline function from Transformers.
from transformers import pipeline

# Load Facebook's BART Large CNN model for abstractive text summarization.
summarizer = pipeline(
    "summarization",
    model="facebook/bart-large-cnn"
)

type(summarizer)

"""**Generate Summary for One Paper**"""

summary=summarizer(df.iloc[10466]["abstract"],max_length=120,min_length=40)
print(summary)

type(summary)

type(summary[0])

summary[0]["summary_text"]

"""**Summarize All Retrieved Papers**"""

# Display similarity score, paper title, abstract, and generated summary for each retrieved paper.

for score, idx in zip(D[0], I[0]):
    print("Similarity Score :", score)
    print("Paper Title :", df.iloc[idx]["title"])
    print("Paper Abstract :")
    print(df.iloc[idx]["abstract"][:500])

    summary = summarizer(
        df.iloc[idx]["abstract"],
        max_length=120,
        min_length=40
    )

    print("Paper Summary :")
    print(summary[0]["summary_text"])
    print()

"""**Search and Summarize Research Papers**"""

def search_paper_and_summarize(query,k=5):
  query_embedding = model.encode([query])
  faiss.normalize_L2(embeddings)
  D,I = index.search(query_embedding,k)
  for score,idx in zip(D[0],I[0]):
    print("Similarity Score",score)
    print("Paper Title",df.iloc[idx]["title"])
    print("Paper Abstract",df.iloc[idx]["abstract"][:500])
    print()

    summary = summarizer(df.iloc[idx]["abstract"],max_length=120, min_length=40,do_sample=False)
    print("Paper Summary :")
    print(summary[0]["summary_text"])
    print()

search_paper_and_summarize("Deep learning in medical imaging ",k=5)

"""## Keyword Extraction using KeyBERT"""

from keybert import KeyBERT

kw_model = KeyBERT()

type(kw_model)

text = df.iloc[10466]["abstract"]
keywords = kw_model.extract_keywords(text)
print(keywords)

print(type(keywords))

print(type(keywords[0]))

"""**Extract Keywords using KeyBERT (n-gram based)**"""

keywords = kw_model.extract_keywords(
    text,
    keyphrase_ngram_range=(1, 3),
    stop_words="english"
)
print(keywords)

"""**Search, Summarize and Extract Keywords**"""

def search_summarize_extract_keywords(query, k=5):
    query_embedding = model.encode([query])
    faiss.normalize_L2(query_embedding)
    D, I = index.search(query_embedding, k)

    for score, idx in zip(D[0], I[0]):
        print("Similarity score:", score)
        print("Title:", df.iloc[idx]["title"])
        print("Abstract:", df.iloc[idx]["abstract"][:500])
        print()

        summary = summarizer(
            df.iloc[idx]["abstract"],
            max_length=120,
            min_length=40
        )

        print("Summary:")
        print(summary[0]["summary_text"])
        print()

        keywords = kw_model.extract_keywords(
            df.iloc[idx]["abstract"],
            keyphrase_ngram_range=(1, 3),
            stop_words="english"
        )

        print("Keywords:")

        for k_word, score in keywords:
            print(k_word)

        print("-" * 80)

search_summarize_extract_keywords("deep learning for medical image analysis", k=5)

"""## Explainable Research Paper Recommendation System

**Research Paper Insight Generation**
"""

def generate_insight(query, keywords, score):

    top_keywords = ", ".join(keywords[:5])

    # interpret similarity
    if score > 0.75:
        strength = "Very High"
        reason = "strong semantic match with your query"
    elif score > 0.60:
        strength = "High"
        reason = "good contextual similarity with your topic"
    else:
        strength = "Moderate"
        reason = "partial relevance to your query"

    return f"""
PAPER RELEVANCE ANALYSIS
----------------------------

Query Match Level : {strength}
Similarity Score   : {round(score, 4)}

Key Topics Identified:
{top_keywords}

Conclusion:
The paper demonstrates {reason} with respect to the input query.
It is therefore considered relevant for recommendation.
"""

"""**Test on Single Paper**"""

sample_index = 0

title = df.iloc[sample_index]["title"]
abstract = df.iloc[sample_index]["abstract"]

"""**Extract keywords**"""

keywords = kw_model.extract_keywords(
    abstract,
    keyphrase_ngram_range=(1, 3),
    stop_words="english"
)

keyword_list = [k for k, _ in keywords]

"""**Get similarity score**"""

query = "deep learning medical imaging"

query_embedding = model.encode([query])
paper_embedding = model.encode([abstract])

import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

score = cosine_similarity(query_embedding, paper_embedding)[0][0]

"""**Generate Insight**"""

print("TITLE:", title)
print("\nKEYWORDS:", keyword_list)

print("\nINSIGHT:\n")
print(generate_insight(query, keyword_list, score))

def search_paper_with_insight(query, k=5):
    query_embedding = model.encode([query])
    faiss.normalize_L2(query_embedding)
    D, I = index.search(query_embedding, k)

    for score, idx in zip(D[0], I[0]):
        title = df.iloc[idx]["title"]
        abstract = df.iloc[idx]["abstract"]

        print("TITLE:", title)
        print("\nSIMILARITY SCORE:", score)
        print("\nABSTRACT:", abstract[:500])
        print()

        keywords = kw_model.extract_keywords(
            abstract,
            keyphrase_ngram_range=(1, 3),
            stop_words="english"
        )
        keyword_list = [k for k, _ in keywords]

        print("\nKEYWORDS:", keyword_list)

        print("\nWHY THIS PAPER:")
        print(generate_insight(query, keyword_list, score))

        print("-"*80)

search_paper_with_insight("deep learning for medical imaging")

"""## Research Paper Difficulty Analyzer"""

!pip install textstat

import textstat
import re

def analyze_difficulty(text, keywords):

    sentences = re.split(r'[.!?]+', text)
    sentences = [s for s in sentences if s.strip()]

    avg_sentence_length = len(text.split()) / len(sentences) if len(sentences) > 0 else 0
    abstract_length = len(text.split())
    readability = textstat.flesch_reading_ease(text)
    keyword_count = len(keywords)

    sentence_score = min(avg_sentence_length / 40, 1)
    length_score = min(abstract_length / 300, 1)
    keyword_score = min(keyword_count / 15, 1)
    readability_score = max(0, (100 - readability) / 100)

    difficulty_score = (
        0.30 * sentence_score +
        0.30 * keyword_score +
        0.20 * length_score +
        0.20 * readability_score
    ) * 10

    if difficulty_score < 4:
        level = "Beginner"
    elif difficulty_score < 7:
        level = "Intermediate"
    else:
        level = "Advanced"

    return level, round(difficulty_score, 2)

def get_research_paper_insights(query, k=5):
    query_embedding = model.encode([query])
    faiss.normalize_L2(query_embedding)
    D, I = index.search(query_embedding, k)

    for score, idx in zip(D[0], I[0]):
        title = df.iloc[idx]["title"]
        abstract = df.iloc[idx]["abstract"]

        print("TITLE:", title)
        print("\nSIMILARITY SCORE:", score)
        print("\nABSTRACT:", abstract[:500])
        print()

        keywords = kw_model.extract_keywords(
            abstract,
            keyphrase_ngram_range=(1, 3),
            stop_words="english"
        )
        keyword_list = [k for k, _ in keywords]

        print("\nKEYWORDS:", keyword_list)

        print("\nWHY THIS PAPER:")
        print(generate_insight(query, keyword_list, score))

        level, score_diff = analyze_difficulty(abstract, keyword_list)

        print("\nDIFFICULTY ANALYSIS:")
        print("Level:", level)
        print("Score:", score_diff)
        print()
        print("-"*80)
        print()

get_research_paper_insights("deep learning for medical imaging")

